sudo: required

language: go

go:
  - 1.7

services:
  - docker

env:
  global:
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"
    - secure: STTpq+sXFaJNaFLmBfzerIWg37Eb/gVbR2lt8k1weK3/ogTgP9TXO23iYxLmcp8WEP27Av+zpOAx/fpIcw7be1sY1Nk63YAzIby0KCUbt7rwPvVaB/5UtX8+PIJ2WNM+ETBfP03V3jaIaT9Hc9YH0WnqC4tlpCfloMM6mb0MINyeL9l6oid1e8oWT0QK4LOCtggA+daktMOmw3UmjQXoflZmSlX89j/FS70BAzRnJtKPO/DFgCEw5wjgyOJ6b2heZiqEDLN1loKGV+8rMcwK4xuqV3cB3khdPI4DdrTfI43F/hQqMLkwZ7XEVhrcOqKtISjT4lHX8KyTaN71u0lT4FMqw8d8S/4rdb04M7DZ5/LL70RPuB1B8XglC6Hayqnvaa7tj7EpkCFEVzbXA6lLwdF7lfWvO2eaLsdC8ISn5gjJVBUJoL/6EIU0wmv3tDPm3Xmv/iNZIb1XoDYASZ+O2w5kV2EGd62xV0uGLdy3u2okARIOl9Tc5v/Bjlz4uJIM7g7SSawi8uGvyLJpsgfFc1DX/2tiU5advlq7FgZCWau96JV4/SKl8GPWARwUYYuumME7ZDyJiO41CMcBQuA43GsFzoAmBl/kmG+QUuNxoYexvMYu7mOTMgL58uQFdKnNHeh08P+Gdcdw6s5zNXzNF7JTJAwy/DnHIYvpdgkKiBs=
    - secure: Yiy1DOi9ZKTMaeapEHemJT1GQ44O+lEkFpjVuxogCgWaJq6a11KLbvj7y0Ib6v6XsBcOJWStt9KYnyLLozhbou4kuZnnYpJUa6Tg+uTzG9KtdSHsQoqaV3egcaZGuVq2TPDEkLpvwxdJOkynynneF79GgbVg37s0q16mH9nm0WNmkgupSg2QLeAhnJtTr/OWIoN2Ih1wIwtUkMI5DR3jHQeF80hPKzjZxE2Fw8bqycKtHMRy5Sh39MkR3Ii74ncYJCI8+PaPRLh9cfXF6rwsO3uY2m98Gmc821f07hEzGurmAQE+lNucV+B45kJA9GgD3wp3BK8eNcl5s8DadYBmxUM2MNqY3c96WoRIz4qWDc9Yy9haiH97By0MHvJRmgrcp31wD1hAerasJw3C3oXpw4sBR+1RyjHL1J6HOLzbAA/gY48/xIvBu2Ky5OcGh1Oi8WE5EDRCX44U+H6xe76g26RCl3cdZij9+SnlKP+l3albzUoRxJcrtkq0z4d31g5H09QypMpZcUPwiu8z543L5pzbAIrCfbpELAHVMYBbQtBeG7P8+JpcYDg7luV4EGLv9HomdBLK0N0EAdHliAv8kjUkoJh6fyk3n68Ups143n0nEnWTzXQf9kzQ541kuchVSodFQkc7X/sesl56885BXq2AMZoOw7TKtpTRhbr2bpI=
    - secure: pIloROw6i89nmoici5INAzpqIPnrznypPjHzB5/PH97h4DNqvcywNWLNVBB7MFcVsQojhlzv47gTqhrefb5GYl+laIX8x1/30IHPBGbtU28GrgKVGF0MpvViib9x6oQmJU5fwu99bi4PjUqE0KATeCpNryS0/0ZfN7PUjjQ/Pm/rXx/rWZvZbUEn5V9xiHQvLtc+aPBTVpXnU5xjxOUwnSohrpGKaOc33n4aFsPC8UCoXlEqZ1Gp9BqebOozv41pPnQjgOxPDkJyUjhMYZ2JRNOA0H5JnO1HSKJJCX9uCpNmtj4iBnR5TykdrHySnDbfL88399I/gL/yVcqSTpvlkfHGsx9VxfMhKnK96lz4axEsKhzRETPpkVmqB3SI2j2w48CIjgvo8oo4OfcletFgnBVG7VynPN/jt/VdnErMZ+BHj+ueXQDYaEcI4jluPfjz7LytnCa4T2Bsgl/DXSSQFSHkvsC6K7Q9V73TY8IKdyqRCnv4TYFrUA75+CAvaydu5JTnslq9TWbPzQFl9Boj+Ap7iuZWOg9DBK3T3THfu/ZxuHfLFbPpSsksONFEifdpgPKhksBe2na9CX//3Oa2pu1tmNTU2aBDWt+aG1+P+UL5yUJq7yeoHnMzd8VfBBlXdPRfnCIU0PyVmjslDGKPY05lEoqOkNB4ju2Sgut53TY=

script:
  - GOBUILD=${GOBUILD} make build
  - ls -la backend/build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS DOCKER_EMAIL=$DOCKER_EMAIL TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS DOCKER_EMAIL=$DOCKER_EMAIL TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make docker DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS DOCKER_EMAIL=$DOCKER_EMAIL TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  - provider: releases
    api_key: ${GITHUB_API_KEY}
    file:
      - backend/build/hashi-ui-linux-amd64
      - backend/build/hashi-ui-windows-amd64
      - backend/build/hashi-ui-darwin-amd64
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
